# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://github.com/yourname/yourmod/issues" #optional

[[mods]] #mandatory
modId="sovatab" #mandatory
version="1.0.0" #mandatory
displayName="sovaTab" #mandatory
description='''Был создан индивидуально для сервер TwitchWorld'''

[[dependencies.sovatab]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[39,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.sovatab]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"